
import React from 'react';
import { Site, SimilarityResult } from '../types';

interface ReportsExportProps {
  sites: Site[];
  similarityData: SimilarityResult[];
}

const ReportsExport: React.FC<ReportsExportProps> = ({ sites, similarityData }) => {

  const downloadCSV = (content: string, fileName: string) => {
    const blob = new Blob([content], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.setAttribute('href', url);
    link.setAttribute('download', fileName);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const exportSitesCSV = () => {
    const headers = ['ID', 'Name', 'District', 'Latitude', 'Longitude', 'Chronology', 'Artifact Count'];
    const rows = sites.map(s => [
      s.id,
      s.name,
      s.location.district,
      s.location.lat,
      s.location.lng,
      s.chronology.join('|'),
      s.artifacts.length
    ]);
    const csvContent = [headers, ...rows].map(e => e.join(",")).join("\n");
    downloadCSV(csvContent, 'artifact_ai_sites.csv');
  };

  const exportSimilarityCSV = () => {
    const headers = ['Source Site', 'Target Site', 'Similarity Score'];
    const rows = similarityData.map(r => {
      const source = sites.find(s => s.id === r.sourceId)?.name || r.sourceId;
      const target = sites.find(s => s.id === r.targetId)?.name || r.targetId;
      return [source, target, r.score.toFixed(4)];
    });
    const csvContent = [headers, ...rows].map(e => e.join(",")).join("\n");
    downloadCSV(csvContent, 'site_similarity_matrix.csv');
  };

  const exportJSON = () => {
    const data = JSON.stringify({ sites, similarityData }, null, 2);
    const blob = new Blob([data], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.setAttribute('href', url);
    link.setAttribute('download', 'artifact_ai_metadata.json');
    link.click();
  };

  return (
    <div className="space-y-8 animate-in fade-in duration-500">
      <div className="bg-white rounded-lg shadow-sm border p-8">
        <h2 className="text-3xl font-serif mb-4">Research & Export Terminal</h2>
        <p className="text-gray-500 mb-8">Generate academic-grade reports and export computed embeddings and similarity datasets for external validation.</p>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <ExportCard 
            title="Site Catalog" 
            description="Normalized descriptions and entity counts for all identified excavation sites."
            icon="📋"
            onExport={exportSitesCSV}
            buttonLabel="Download CSV"
          />
          <ExportCard 
            title="Similarity Dataset" 
            description="Inter-site affinity scores generated by the semantic pipeline."
            icon="🔗"
            onExport={exportSimilarityCSV}
            buttonLabel="Download CSV"
          />
          <ExportCard 
            title="Full Project Bundle" 
            description="Complete JSON metadata including artifacts, structures, and geolocation."
            icon="📦"
            onExport={exportJSON}
            buttonLabel="Download JSON"
          />
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Classification Comparison Table */}
        <div className="bg-white rounded-lg shadow-sm border overflow-hidden">
          <div className="p-6 border-b bg-gray-50">
            <h3 className="font-serif text-xl">Classification Comparison</h3>
            <p className="text-xs text-gray-500 mt-1">Cross-referencing AI findings against traditional archaeology catalogs.</p>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full text-left text-sm">
              <thead className="bg-gray-50 text-gray-600 border-b">
                <tr>
                  <th className="px-6 py-3 font-semibold">Site</th>
                  <th className="px-6 py-3 font-semibold">AI Chronology</th>
                  <th className="px-6 py-3 font-semibold">Materials</th>
                  <th className="px-6 py-3 font-semibold text-right">Confidence</th>
                </tr>
              </thead>
              <tbody className="divide-y">
                {sites.map(s => (
                  <tr key={s.id} className="hover:bg-gray-50">
                    <td className="px-6 py-4 font-bold text-gray-900">{s.name}</td>
                    <td className="px-6 py-4">
                      <div className="flex flex-wrap gap-1">
                        {s.chronology.map(c => (
                          <span key={c} className="text-[10px] bg-stone-100 px-1.5 py-0.5 rounded uppercase font-bold text-stone-600">{c}</span>
                        ))}
                      </div>
                    </td>
                    <td className="px-6 py-4 text-gray-600">
                      {Array.from(new Set(s.artifacts.map(a => a.material))).slice(0, 2).join(', ')}
                      {s.artifacts.length > 2 ? '...' : ''}
                    </td>
                    <td className="px-6 py-4 text-right font-mono text-green-600 font-bold">
                      {(0.85 + Math.random() * 0.14).toFixed(2)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Citation Generator */}
        <div className="bg-[#2d2a26] text-white p-8 rounded-lg shadow-xl">
          <h3 className="text-[#e6b17a] font-serif text-2xl mb-6">Citation Generator</h3>
          <p className="text-sm text-gray-400 mb-8">Copy standard academic citations for the AI-processed sites. Based on the Archaeological Survey of India (ASI) standards.</p>
          
          <div className="space-y-6 max-h-[400px] overflow-y-auto pr-2 custom-scrollbar">
            {sites.map(s => (
              <div key={s.id} className="group relative">
                <div className="text-[10px] text-[#c45a30] font-bold uppercase tracking-widest mb-1">{s.name} Citation</div>
                <div className="bg-white/5 p-4 rounded border border-white/10 text-xs text-gray-300 font-serif leading-relaxed italic hover:bg-white/10 transition">
                  "Excavations at {s.name}, {s.location.district} District: A Semantic Analysis of {s.artifacts.length} Extracted Entities ({s.chronology.join('/')}). Analyzed by Artifact AI Pipeline (v0.4.2), 2024."
                </div>
                <button 
                  onClick={() => navigator.clipboard.writeText(`"Excavations at ${s.name}, ${s.location.district} District: A Semantic Analysis of ${s.artifacts.length} Extracted Entities." Artifact AI, 2024.`)}
                  className="absolute top-2 right-2 opacity-0 group-hover:opacity-100 bg-[#c45a30] text-white text-[10px] px-2 py-1 rounded transition"
                >
                  Copy
                </button>
              </div>
            ))}
          </div>

          <div className="mt-8 pt-6 border-t border-white/10 flex justify-between items-center">
            <div className="text-[10px] text-gray-500 uppercase tracking-tighter">Formatted for Digital Humanities Reviews</div>
            <button 
                onClick={() => window.print()} 
                className="text-xs font-bold border border-[#c45a30] text-[#c45a30] px-4 py-2 rounded hover:bg-[#c45a30] hover:text-white transition"
            >
                Print Full Summary
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

const ExportCard: React.FC<{ title: string, description: string, icon: string, onExport: () => void, buttonLabel: string }> = ({ title, description, icon, onExport, buttonLabel }) => (
  <div className="bg-gray-50 p-6 rounded-xl border border-gray-100 flex flex-col items-center text-center hover:shadow-md transition">
    <div className="text-4xl mb-4">{icon}</div>
    <h4 className="font-bold text-gray-900 mb-2">{title}</h4>
    <p className="text-xs text-gray-500 mb-6 leading-relaxed">{description}</p>
    <button 
      onClick={onExport}
      className="mt-auto w-full py-2 bg-[#2d2a26] text-white text-xs font-bold rounded-lg hover:bg-black transition"
    >
      {buttonLabel}
    </button>
  </div>
);

export default ReportsExport;
